# Generated by Django 4.2.13 on 2026-05-09 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_email", models.EmailField(blank=True, max_length=254)),
                ("user_role", models.CharField(blank=True, max_length=20)),
                ("clinic_name", models.CharField(blank=True, max_length=200)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login Failed"),
                            ("password_changed", "Password Changed"),
                            ("password_reset", "Password Reset"),
                            ("create", "Create"),
                            ("read", "Read"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("restore", "Restore"),
                            ("appointment_booked", "Appointment Booked"),
                            ("appointment_cancelled", "Appointment Cancelled"),
                            ("appointment_rescheduled", "Appointment Rescheduled"),
                            ("appointment_completed", "Appointment Completed"),
                            ("invoice_created", "Invoice Created"),
                            ("payment_recorded", "Payment Recorded"),
                            ("prescription_created", "Prescription Created"),
                            ("prescription_updated", "Prescription Updated"),
                            ("prescription_pdf", "Prescription PDF Downloaded"),
                            ("staff_added", "Staff Added"),
                            ("staff_role_changed", "Staff Role Changed"),
                            ("staff_deactivated", "Staff Deactivated"),
                            ("data_exported", "Data Exported"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(db_index=True, max_length=50)),
                (
                    "resource_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("resource_repr", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("changes", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "timestamp"],
                        name="activity_lo_clinic__6edd27_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="activity_lo_user_id_e40ffe_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="activity_lo_action_fe3d88_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="activity_lo_resourc_31a457_idx",
                    ),
                    models.Index(
                        fields=["clinic", "action", "timestamp"],
                        name="activity_lo_clinic__f87378_idx",
                    ),
                ],
            },
        ),
    ]
