# Generated by Django 4.2.13 on 2026-05-09 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        ("appointments", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("visit_date", models.DateField(db_index=True)),
                ("visit_number", models.PositiveIntegerField(default=1)),
                ("chief_complaint", models.TextField()),
                ("history_of_present_illness", models.TextField(blank=True)),
                ("generals", models.TextField(blank=True)),
                ("particulars", models.TextField(blank=True)),
                ("mentals", models.TextField(blank=True)),
                ("physical_generals", models.TextField(blank=True)),
                ("modalities", models.TextField(blank=True)),
                ("miasmatic_analysis", models.TextField(blank=True)),
                ("totality_of_symptoms", models.TextField(blank=True)),
                ("repertorisation_notes", models.TextField(blank=True)),
                ("rubrics", models.JSONField(default=list)),
                ("examination_findings", models.TextField(blank=True)),
                ("vitals", models.JSONField(default=dict)),
                ("provisional_diagnosis", models.CharField(blank=True, max_length=300)),
                ("differential_diagnosis", models.TextField(blank=True)),
                ("next_visit_date", models.DateField(blank=True, null=True)),
                ("follow_up_instructions", models.TextField(blank=True)),
                ("dietary_advice", models.TextField(blank=True)),
                ("lifestyle_advice", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescription",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "prescriptions",
            },
        ),
        migrations.CreateModel(
            name="Remedy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "abbreviation",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("full_name", models.CharField(blank=True, max_length=300)),
                ("source", models.CharField(blank=True, max_length=100)),
                (
                    "kingdom",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plant", "Plant"),
                            ("mineral", "Mineral"),
                            ("animal", "Animal"),
                            ("nosode", "Nosode"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_remedies",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "remedies",
            },
        ),
        migrations.CreateModel(
            name="PrescriptionRemedy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("potency", models.CharField(max_length=20)),
                (
                    "potency_scale",
                    models.CharField(
                        choices=[
                            ("X", "X (Decimal)"),
                            ("C", "C (Centesimal)"),
                            ("M", "M (Milliesimal)"),
                            ("LM", "LM/Q (Fifty Millesimal)"),
                            ("CM", "CM"),
                        ],
                        default="C",
                        max_length=5,
                    ),
                ),
                ("dose", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=100)),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("oral", "Oral"),
                            ("sublingual", "Sublingual"),
                            ("olfaction", "Olfaction"),
                        ],
                        default="sublingual",
                        max_length=20,
                    ),
                ),
                (
                    "remedy_type",
                    models.CharField(
                        choices=[
                            ("constitutional", "Constitutional"),
                            ("acute", "Acute"),
                            ("intercurrent", "Intercurrent"),
                            ("organ_remedy", "Organ Remedy"),
                            ("drainage", "Drainage"),
                            ("nosode", "Nosode"),
                            ("other", "Other"),
                        ],
                        default="constitutional",
                        max_length=30,
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remedies",
                        to="prescriptions.prescription",
                    ),
                ),
                (
                    "remedy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescription_uses",
                        to="prescriptions.remedy",
                    ),
                ),
            ],
            options={
                "db_table": "prescription_remedies",
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddIndex(
            model_name="remedy",
            index=models.Index(fields=["name"], name="remedies_name_bf7358_idx"),
        ),
        migrations.AddIndex(
            model_name="remedy",
            index=models.Index(
                fields=["abbreviation"], name="remedies_abbrevi_25dbc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["clinic", "patient"], name="prescriptio_clinic__91d245_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["clinic", "doctor", "visit_date"],
                name="prescriptio_clinic__e6a26c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["clinic", "visit_date"], name="prescriptio_clinic__f84f86_idx"
            ),
        ),
    ]
