# Generated by Django 4.2.13 on 2026-05-09 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="clinics/logos/"
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=300)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("website", models.URLField(blank=True)),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("pincode", models.CharField(max_length=20)),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=50)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("language", models.CharField(default="en", max_length=10)),
                ("business_hours", models.JSONField(default=dict)),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("starter", "Starter (3 Doctors)"),
                            ("professional", "Professional (10 Doctors)"),
                            ("enterprise", "Enterprise (Unlimited)"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("subscription_start", models.DateField(blank=True, null=True)),
                ("subscription_end", models.DateField(blank=True, null=True)),
                ("max_doctors", models.PositiveIntegerField(default=1)),
                ("max_patients", models.PositiveIntegerField(default=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("trial", "Trial"),
                            ("expired", "Expired"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("registration_number", models.CharField(blank=True, max_length=100)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_clinics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic",
                "db_table": "clinics",
            },
        ),
        migrations.CreateModel(
            name="ClinicSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "appointment_duration_minutes",
                    models.PositiveIntegerField(default=30),
                ),
                ("advance_booking_days", models.PositiveIntegerField(default=30)),
                ("allow_walk_ins", models.BooleanField(default=True)),
                ("queue_enabled", models.BooleanField(default=True)),
                ("auto_confirm_appointments", models.BooleanField(default=False)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("whatsapp_enabled", models.BooleanField(default=False)),
                ("email_enabled", models.BooleanField(default=True)),
                ("reminder_hours_before", models.JSONField(default=list)),
                ("primary_color", models.CharField(default="#2D6A4F", max_length=7)),
                ("invoice_prefix", models.CharField(default="INV", max_length=10)),
                ("prescription_header", models.TextField(blank=True)),
                ("prescription_footer", models.TextField(blank=True)),
                ("twilio_sid", models.CharField(blank=True, max_length=100)),
                ("twilio_token", models.CharField(blank=True, max_length=100)),
                ("whatsapp_api_key", models.CharField(blank=True, max_length=200)),
                (
                    "clinic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "db_table": "clinic_settings",
            },
        ),
        migrations.AddIndex(
            model_name="clinic",
            index=models.Index(fields=["slug"], name="clinics_slug_6b44da_idx"),
        ),
        migrations.AddIndex(
            model_name="clinic",
            index=models.Index(fields=["status"], name="clinics_status_953dfa_idx"),
        ),
        migrations.AddIndex(
            model_name="clinic",
            index=models.Index(fields=["city"], name="clinics_city_a63783_idx"),
        ),
    ]
