"""
apps/billing/models.py
Invoice generation, payment tracking, and subscription management.
"""

from django.db import models
from django.core.validators import MinValueValidator

from apps.core.models import TenantModel, UUIDModel, TimeStampedModel


class InvoiceStatus(models.TextChoices):
    DRAFT = "draft", "Draft"
    SENT = "sent", "Sent"
    PAID = "paid", "Paid"
    PARTIALLY_PAID = "partial", "Partially Paid"
    OVERDUE = "overdue", "Overdue"
    CANCELLED = "cancelled", "Cancelled"
    REFUNDED = "refunded", "Refunded"


class PaymentMethod(models.TextChoices):
    CASH = "cash", "Cash"
    CARD = "card", "Card"
    UPI = "upi", "UPI"
    NEFT = "neft", "NEFT/RTGS"
    INSURANCE = "insurance", "Insurance"
    OTHER = "other", "Other"


class Invoice(TenantModel):
    """
    Invoice for a patient visit or service.
    Supports partial payments.
    """

    patient = models.ForeignKey(
        "patients.Patient", on_delete=models.CASCADE, related_name="invoices"
    )
    appointment = models.ForeignKey(
        "appointments.Appointment",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="invoices",
    )
    doctor = models.ForeignKey(
        "accounts.User", on_delete=models.SET_NULL, null=True, blank=True, related_name="+"
    )

    # Invoice identity
    invoice_number = models.CharField(max_length=30, unique=True, db_index=True)
    invoice_date = models.DateField(db_index=True)
    due_date = models.DateField(null=True, blank=True)

    # Amounts
    subtotal = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    discount_percent = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    tax_percent = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    tax_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    paid_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    # Status
    status = models.CharField(
        max_length=20, choices=InvoiceStatus.choices, default=InvoiceStatus.DRAFT
    )

    # Notes
    notes = models.TextField(blank=True)
    terms_conditions = models.TextField(blank=True)

    # Generated by
    created_by = models.ForeignKey(
        "accounts.User", on_delete=models.SET_NULL, null=True, related_name="+"
    )

    class Meta:
        db_table = "invoices"
        indexes = [
            models.Index(fields=["clinic", "invoice_date"]),
            models.Index(fields=["clinic", "patient"]),
            models.Index(fields=["clinic", "status"]),
        ]

    def __str__(self):
        return f"{self.invoice_number} | {self.patient} | ₹{self.total_amount}"

    @property
    def balance_due(self):
        return self.total_amount - self.paid_amount

    @property
    def is_paid(self):
        return self.paid_amount >= self.total_amount

    def generate_invoice_number(self):
        from apps.clinics.models import ClinicSettings
        try:
            prefix = self.clinic.settings.invoice_prefix
        except Exception:
            prefix = "INV"
        count = Invoice.objects.filter(clinic=self.clinic).count() + 1
        return f"{prefix}-{count:06d}"

    def save(self, *args, **kwargs):
        if not self.invoice_number:
            self.invoice_number = self.generate_invoice_number()
        super().save(*args, **kwargs)


class InvoiceLineItem(UUIDModel, TimeStampedModel):
    """Individual line items on an invoice."""

    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name="line_items")
    description = models.CharField(max_length=300)
    category = models.CharField(
        max_length=30,
        choices=[
            ("consultation", "Consultation Fee"),
            ("medicine", "Medicine"),
            ("test", "Lab Test"),
            ("procedure", "Procedure"),
            ("other", "Other"),
        ],
        default="consultation",
    )
    quantity = models.PositiveIntegerField(default=1)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        db_table = "invoice_line_items"


class Payment(TenantModel):
    """
    Individual payment record against an invoice.
    Supports partial payments.
    """

    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name="payments")
    patient = models.ForeignKey("patients.Patient", on_delete=models.CASCADE, related_name="payments")
    amount = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0.01)])
    payment_method = models.CharField(max_length=20, choices=PaymentMethod.choices)
    payment_date = models.DateField(db_index=True)
    transaction_id = models.CharField(max_length=200, blank=True)
    reference_number = models.CharField(max_length=200, blank=True)
    notes = models.CharField(max_length=300, blank=True)
    received_by = models.ForeignKey(
        "accounts.User", on_delete=models.SET_NULL, null=True, related_name="+"
    )

    class Meta:
        db_table = "payments"
        indexes = [
            models.Index(fields=["clinic", "payment_date"]),
            models.Index(fields=["clinic", "invoice"]),
        ]


class SubscriptionPlanDetail(UUIDModel, TimeStampedModel):
    """Available subscription plans (managed by Super Admin)."""

    name = models.CharField(max_length=100)
    code = models.CharField(max_length=30, unique=True)
    price_monthly = models.DecimalField(max_digits=10, decimal_places=2)
    price_yearly = models.DecimalField(max_digits=10, decimal_places=2)
    max_doctors = models.PositiveIntegerField()
    max_patients = models.PositiveIntegerField()
    features = models.JSONField(default=list)
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = "subscription_plan_details"


class ClinicSubscription(UUIDModel, TimeStampedModel):
    """Subscription record per clinic."""

    clinic = models.ForeignKey(
        "clinics.Clinic", on_delete=models.CASCADE, related_name="subscriptions"
    )
    plan = models.ForeignKey(SubscriptionPlanDetail, on_delete=models.PROTECT)
    billing_cycle = models.CharField(
        max_length=10, choices=[("monthly", "Monthly"), ("yearly", "Yearly")], default="monthly"
    )
    start_date = models.DateField()
    end_date = models.DateField()
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2)
    payment_reference = models.CharField(max_length=200, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = "clinic_subscriptions"