# Generated by Django 4.2.13 on 2026-05-09 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "patient_code",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("first_name", models.CharField(db_index=True, max_length=100)),
                ("last_name", models.CharField(db_index=True, max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("alternate_phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=20)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("constitution", models.CharField(blank=True, max_length=200)),
                ("miasm", models.CharField(blank=True, max_length=200)),
                ("thermal", models.CharField(blank=True, max_length=50)),
                ("diathesis", models.CharField(blank=True, max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("walk_in", "Walk-in"),
                            ("referral", "Referral"),
                            ("online", "Online"),
                            ("other", "Other"),
                        ],
                        default="walk_in",
                        max_length=50,
                    ),
                ),
                ("referral_by", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("consent_given", models.BooleanField(default=False)),
                ("consent_date", models.DateField(blank=True, null=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "patients",
            },
        ),
        migrations.CreateModel(
            name="PatientAttachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="patients/attachments/%Y/%m/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=100)),
                ("file_size", models.PositiveIntegerField()),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("report", "Lab Report"),
                            ("scan", "Scan/X-Ray"),
                            ("prescription", "Old Prescription"),
                            ("identity", "ID Document"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="patients.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "patient_attachments",
            },
        ),
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chief_complaint", models.TextField()),
                ("history_of_present_illness", models.TextField(blank=True)),
                ("onset", models.CharField(blank=True, max_length=200)),
                ("duration", models.CharField(blank=True, max_length=100)),
                ("modalities", models.TextField(blank=True)),
                ("past_medical_history", models.TextField(blank=True)),
                ("past_surgical_history", models.TextField(blank=True)),
                ("family_history", models.TextField(blank=True)),
                ("personal_history", models.TextField(blank=True)),
                ("drug_history", models.TextField(blank=True)),
                ("allergies", models.JSONField(default=list)),
                ("systemic_review", models.JSONField(default=dict)),
                ("appetite", models.CharField(blank=True, max_length=200)),
                ("thirst", models.CharField(blank=True, max_length=200)),
                ("sleep_pattern", models.TextField(blank=True)),
                ("dreams", models.TextField(blank=True)),
                ("perspiration", models.TextField(blank=True)),
                ("stool_urine", models.TextField(blank=True)),
                ("menstrual_history", models.TextField(blank=True)),
                ("mental_generals", models.TextField(blank=True)),
                ("emotional_state", models.TextField(blank=True)),
                ("physical_examination", models.TextField(blank=True)),
                ("vitals", models.JSONField(default=dict)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_history",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "medical_histories",
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["clinic", "phone"], name="patients_clinic__63b618_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["clinic", "email"], name="patients_clinic__2d56fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["clinic", "first_name", "last_name"],
                name="patients_clinic__7f1a8a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["clinic", "patient_code"], name="patients_clinic__1141ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["primary_doctor"], name="patients_primary_7cecda_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="patient",
            unique_together={("clinic", "patient_code")},
        ),
        migrations.AddIndex(
            model_name="medicalhistory",
            index=models.Index(
                fields=["clinic", "patient"], name="medical_his_clinic__2313d3_idx"
            ),
        ),
    ]
