# Generated by Django 4.2.13 on 2026-05-09 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slot_duration_minutes", models.PositiveIntegerField(default=30)),
                ("max_patients_per_slot", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "doctor_schedules",
                "indexes": [
                    models.Index(
                        fields=["clinic", "doctor", "day_of_week"],
                        name="doctor_sche_clinic__3b5877_idx",
                    )
                ],
                "unique_together": {("clinic", "doctor", "day_of_week", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="DoctorLeave",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("leave_date", models.DateField(db_index=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Day"),
                            ("morning", "Morning"),
                            ("evening", "Evening"),
                            ("emergency", "Emergency"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=300)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "doctor_leaves",
                "unique_together": {("clinic", "doctor", "leave_date")},
            },
        ),
        migrations.CreateModel(
            name="AppointmentQueue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("queue_date", models.DateField(db_index=True)),
                ("current_token", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("average_wait_minutes", models.PositiveIntegerField(default=30)),
                ("is_accepting", models.BooleanField(default=True)),
                ("queue_started_at", models.DateTimeField(blank=True, null=True)),
                ("queue_paused_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "appointment_queues",
                "unique_together": {("clinic", "doctor", "queue_date")},
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("appointment_date", models.DateField(db_index=True)),
                ("appointment_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("new", "New Patient"),
                            ("followup", "Follow-Up"),
                            ("emergency", "Emergency"),
                            ("teleconsult", "Tele-Consultation"),
                        ],
                        default="followup",
                        max_length=20,
                    ),
                ),
                ("token_number", models.PositiveIntegerField(blank=True, null=True)),
                ("queue_position", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("chief_complaint", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("consultation_ended_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=300)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_24h_sent", models.BooleanField(default=False)),
                ("reminder_2h_sent", models.BooleanField(default=False)),
                (
                    "booked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booked_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
                (
                    "rescheduled_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rescheduled_to",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "db_table": "appointments",
                "indexes": [
                    models.Index(
                        fields=["clinic", "appointment_date"],
                        name="appointment_clinic__94caa1_idx",
                    ),
                    models.Index(
                        fields=["clinic", "doctor", "appointment_date"],
                        name="appointment_clinic__eee0f3_idx",
                    ),
                    models.Index(
                        fields=["clinic", "patient"],
                        name="appointment_clinic__564357_idx",
                    ),
                    models.Index(
                        fields=["clinic", "status"],
                        name="appointment_clinic__13de9b_idx",
                    ),
                    models.Index(
                        fields=["clinic", "appointment_date", "status"],
                        name="appointment_clinic__d64859_idx",
                    ),
                ],
            },
        ),
    ]
